# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "2.0.0rc2" %}

package:
  name: matplotlib
  version: {{ version }}

source:
  fn: matplotlib-{{ version }}.tar.gz
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: ba3bba07746152f34199aba83363923ca26767a2817914d86efcc7a06caf7536
  patches:
    # Find libpng on Windows.
    - setupext.patch  # [win]
    # A patch to make Qt4Agg the default backend.
    - cfg_qt4agg.patch  # [linux]
    # Patches the matplotlibrc template to default to Qt4.
    - rctmp_pyside.patch  # [not osx]
    # Removes framework check from osx backend (seems unneeded)
    - osx-frame.patch  # [osx]

build:
    number: 2

requirements:
  build:
    - python
    - setuptools
    - pkg-config  # [not win]
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - python-dateutil
    - freetype 2.7
    - msinttypes  # [win and py<35]
    - cycler >=0.10
    - nose
    - pyparsing
    - pytz
    #- py2cairo  # [linux and py2k]
    - libpng >=1.6.28,<1.7
    - zlib 1.2.8  # [win]
    - pyqt 5.6.*  # [not osx]
    - tk 8.5.*  # [linux]
    - functools32  # [py2k]
    - subprocess32  # [py2k and unix]
    - icu 58.*  # [linux]
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - setuptools
    - cycler >=0.10
    - python-dateutil
    - freetype 2.7
    - pytz
    - pyparsing
    #- py2cairo  # [linux and py2k]
    - libpng >=1.6.28,<1.7
    - pyqt 5.6.*  # [not osx]
    - tk 8.5.*  # [linux]
    - functools32  # [py2k]
    - subprocess32  # [py2k and unix]
    - icu 58.*  # [linux]
    - tornado

test:
  imports:
    - matplotlib
    - matplotlib.pyplot
    - matplotlib._cntr
    - matplotlib._delaunay
    - matplotlib._image
    - matplotlib._path
    - matplotlib._png
    - matplotlib._tri
    - matplotlib.backends._backend_agg
    - matplotlib.ft2font
    - matplotlib.ttconv
    - matplotlib.backends._tkagg  # [not win]
    - mpl_toolkits
    - pylab

about:
  home: http://matplotlib.org/
  license: PSF-based (http://matplotlib.org/users/license.html)
  license_family: PSF
  summary: Publication quality figures in Python
  dev_url: https://github.com/matplotlib/matplotlib/
  doc_url: http://matplotlib.org/contents.html

extra:
  recipe-maintainers:
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
