appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c342c7ad1578b0700314111
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: redV8EPEfpaRtRE8u8jAXiR/Zoxu9TCN6D8ufhSFrkNSZ8hNJRtHzN/RJsY3b/tNr7xCegaP3xk+kfaN3c8C0lW/Y+7ayCI38VVibLNsIvzY8ev2UPHb6oLNkp9mpuXk+5c1CA7aGsvYD6EvNMe1nCdUnopSgDNi5qYWjPFQte2gavgVMJqU4FGiQ1upcW9LGyBepbGauqUAYPkJev4BTMWigSvAYanJdT9rZMdO/z3gjBEcmFQI71JgBC7qyiKLVtIpdhUKlHNZxyIWQItgpm6DJOUS0WJniWZxtmaRfYTzFCdR7lRqBMG6deQiSJxM/dubf3uFVDNPOh7+YA3NQcFMoKm/hVdVEQZBNErqUVlkN2evlGizZZiJAkWTX0u+kaAAxe+fKRvdugL2FWuS6Mt/P/l6vBJLRMBiTSidOplqYwIgufNl9Zuwcl9/9Jq37ec3of7Ul0Sm6BBOrbnhEnsZc8v6raJ7xejd1futEKKvOSIJX/TPfTu5fUDwlcZDM9W2MRLqVR2uOfSIDY8izMvpWXRn8T+F59ZVPsH232evd+zlVNSVvwzKrTGyCSEqz+zXYGtRIjSReSiHXnlFfDtTXDiV6D+4tCKZhaaa3HW27iLwqpBRK7pldXyLWPYmdBybZksKj2wgL8fm3S0dEG/b68bVzUxW54RHaYLoR8A=}
